const exports = {};
const include = function(componentName) {
  exports[componentName] = require('./components/' + componentName);
};

include('AnonymousUser');
include('Audience');
include('Camera');
include('Cards');
include('Checkmark');
include('ChevronIcon');
include('Clipboard');
include('Clock');
include('Close');
include('CopyLink');
include('Delete');
include('Dots');
include('Duplicate');
include('EnvelopeFlying');
include('EnvelopeOpened');
include('FacebookLogo');
include('FacebookMessengerLogo');
include('FilmStrip');
include('Gift');
include('GmailLogo');
include('Group');
include('GroupCircled');
include('GroupSolid');
include('Lock');
include('LockSolid');
include('LuggageCart');
include('MembersSolid');
include('Money');
include('OneLeft');
include('Options');
include('PaperAirplaneImage');
include('Pencil');
include('PermissionEmailEnvelope');
include('PermissionFriends');
include('Platforms');
include('PlusCross');
include('SellOptions');
include('Star');
include('TagFriend');
include('TagFriendSolid');
include('TiltLogo');
include('TiltLogoOutline');
include('TiltLogoTextImage');
include('Triangle');
include('TwitterLogo');
include('UsersTwo');
include('WhatsAppLogo');

module.exports = exports;
